### ISSUE TITLE
Can't installtasks because of IOError

### ISSUE THREAD

**Issue by matthewgo** [jgorset/django-kronos#52]
I'm getting an IOError of "Please specify user or filename to write" when I try to register the tasks with cron. This is raised in the crontab.py file. The crontab app was downloaded along with the installation of kronos.

I got the showtasks and runtasks command to run but I can register the tasks using the installtasks command

Do you guys have an idea how to solve this?.

**Comment by matthewgo** [comment]
I am using Windows btw.

**Comment by jppineda** [comment]
Any solution for this issue?

**Comment by jgorset** [comment]
django-kronos isn't tested on windows. In fact, does Windows even have cron?

**Comment by SteveByerly** [comment]
Python-Crontab does work with Windows, but only offers two non-system methods (tabfile and tab), neither of which are setup to be used with kronos. See https://pypi.python.org/pypi/python-crontab#how-to-use-the-module

There might be some way to add this functionality to kronos, but not as it's currently setup since kronos installs new tasks with:
`tab = crontab.CronTab(user=True)`

I think this issue can be closed.

**Comment by AnandMoorthy** [comment]
Hello folks,

I am also facing the same error, when i execute 

> python manage.py installtasks by a python script using subprocess throwing an error

> raise IOError("Read crontab %s: %s" % (self.user, err))
IOError: Read crontab nobody: You (nobody) are not allowed to use this program (/usr/bin/crontab)

So, is installtasks command running via nobody user? or any explanation to this problem?

**Comment by jgorset** [comment]
Sounds like you're running `python manage.py installtasks` with a user that doesn't have permission to add or read the crontab, @AnandMoorthy.
